language: cpp
dist: focal

os:
  - linux
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-focal-11

    packages:
      - g++-10
      - clang-11
      - libglm-dev
      - libglew2.1
      - libglew-dev
      - libsdl2-2.0.0
      - libfmt-dev
      - libsdl2-dev
      - libdevil1c2
      - libdevil-dev
      - libcairo2
      - libcairo2-dev
      - libyaml-0-2
      - libyaml-dev
      - libpango-1.0-0
      - libpango1.0-dev
      - libpangocairo-1.0-0
      - libflatbuffers-dev
      - libflatbuffers1
      - nlohmann-json3-dev
      - flatbuffers-compiler-dev
      - flatbuffers-compiler
      - libcurlpp-dev
      - libexpected-dev
      
# We attempt to fix an issue with the flatc finder command
script:
  - ${CXX} --version
  - mkdir build && cd build
  - cmake -DFLINE_BUILD_TESTS=on -DFLINE_DO_CHECK_ASAN=off -DFLINE_SET_COVERAGE=off -DFLINE_USE_RELATIVE_PATH=on -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DFLATC_TARGET="" -DFLATBUFFERS_FLATC_EXECUTABLE="/usr/bin/flatc" ..
  - make familyline-tests
  - ./familyline-tests



jobs:
  include:
    - name: gcc
      os: linux
      compiler: gcc
      env:
        - CXX=g++-10
    - name: clang
      os: linux
      compiler: clang
      env:
        - CXX=clang++-11
        - CC=clang-11

cache:
  apt: true
